# Generated by Django 4.1.13 on 2024-05-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dieta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.ImageField(upload_to="media/meal_images/"),
        ),
    ]
