# Generated by Django 4.1.13 on 2024-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dieta", "0002_alter_meal_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
