# Generated by Django 4.1.13 on 2024-05-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dieta", "0003_dietplan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="recipe",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meal", name="calories", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="meal", name="carbohydrates", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="meal", name="fat", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.ImageField(upload_to="meal_images/"),
        ),
        migrations.AlterField(
            model_name="meal", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="meal", name="protein", field=models.IntegerField(),
        ),
    ]
